import i18n from "../components/LangConfig";
let idCounter = 0;

// New Product Database with 5 Categories
// Each product has: ID, Product Name, Category, Price (Rs.), Image, Description

export const ITEMS = [
  // Electronics Category (e1-e20)
  {
    id: "e1",
    imageSrc: "/src/assets/Electronics/Wireless Mouse.jpeg",
    title: "Wireless Mouse",
    price: "Rs. 5,000",
    stars: 4,
    rates: 128,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "High-precision wireless mouse with ergonomic design and long battery life.",
  },
  {
    id: "e2",
    imageSrc: "/src/assets/Electronics/Bluetooth Headphones.webp",
    title: "Bluetooth Headphones",
    price: "Rs. 18,000",
    stars: 5,
    rates: 89,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Premium wireless headphones with noise cancellation and crystal clear sound.",
  },
  {
    id: "e3",
    imageSrc: "/src/assets/Electronics/Smartwatch.jpeg",
    title: "Smartwatch",
    price: "Rs. 45,000",
    stars: 4,
    rates: 156,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Feature-rich smartwatch with health monitoring and fitness tracking.",
  },
  {
    id: "e4",
    imageSrc: "/src/assets/Electronics/Laptop.jpeg",
    title: "Laptop",
    price: "Rs. 350,000",
    stars: 5,
    rates: 67,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "High-performance laptop perfect for work, gaming, and creative tasks.",
  },
  {
    id: "e5",
    imageSrc: "/src/assets/Electronics/Mechanical Keyboard.jpg",
    title: "Mechanical Keyboard",
    price: "Rs. 15,000",
    stars: 4,
    rates: 203,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Professional mechanical keyboard with tactile switches and RGB lighting.",
  },
  {
    id: "e6",
    imageSrc: "/src/assets/Electronics/USB-C Hub.jpeg",
    title: "USB-C Hub",
    price: "Rs. 6,500",
    stars: 4,
    rates: 94,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Multi-port USB-C hub for expanding connectivity options.",
  },
  {
    id: "e7",
    imageSrc: "/src/assets/Electronics/External Hard Drive 1TB.jpeg",
    title: "External Hard Drive 1TB",
    price: "Rs. 14,000",
    stars: 4,
    rates: 178,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Portable 1TB external hard drive with fast data transfer speeds.",
  },
  {
    id: "e8",
    imageSrc: "/src/assets/Electronics/Gaming Mousepad.jpeg",
    title: "Gaming Mousepad",
    price: "Rs. 3,500",
    stars: 4,
    rates: 245,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Large gaming mousepad with precise tracking surface.",
  },
  {
    id: "e9",
    imageSrc: "/src/assets/Electronics/Webcam 1080p.jpg",
    title: "Webcam 1080p",
    price: "Rs. 9,000",
    stars: 4,
    rates: 112,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "High-definition webcam perfect for video calls and streaming.",
  },
  {
    id: "e10",
    imageSrc: "/src/assets/Electronics/Portable Bluetooth Speaker.jpg",
    title: "Portable Bluetooth Speaker",
    price: "Rs. 12,000",
    stars: 4,
    rates: 189,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Compact portable speaker with rich sound and long battery life.",
  },
  {
    id: "e11",
    imageSrc: "/src/assets/Electronics/Noise-Cancelling Earbuds.jpeg",
    title: "Noise-Cancelling Earbuds",
    price: "Rs. 20,000",
    stars: 5,
    rates: 134,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Premium wireless earbuds with active noise cancellation.",
  },
  {
    id: "e12",
    imageSrc: "/src/assets/Electronics/Fitness Smart Band.jpg",
    title: "Fitness Smart Band",
    price: "Rs. 12,500",
    stars: 4,
    rates: 267,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Fitness tracking band with heart rate monitoring and GPS.",
  },
  {
    id: "e13",
    imageSrc: "/src/assets/Electronics/HDMI Cable 2m.jpeg",
    title: "HDMI Cable 2m",
    price: "Rs. 1,500",
    stars: 4,
    rates: 456,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "High-quality HDMI cable for crystal clear audio and video transmission.",
  },
  {
    id: "e14",
    imageSrc: "/src/assets/Electronics/Wireless Charger.webp",
    title: "Wireless Charger",
    price: "Rs. 4,500",
    stars: 4,
    rates: 198,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Fast wireless charging pad compatible with all Qi-enabled devices.",
  },
  {
    id: "e15",
    imageSrc: "/src/assets/Electronics/Action Camera 4K.jpeg",
    title: "Action Camera 4K",
    price: "Rs. 55,000",
    stars: 5,
    rates: 78,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "4K action camera perfect for capturing adventure and sports moments.",
  },
  {
    id: "e16",
    imageSrc: "/src/assets/Electronics/VR Headset.jpg",
    title: "VR Headset",
    price: "Rs. 75,000",
    stars: 4,
    rates: 45,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "Immersive virtual reality headset for gaming and entertainment.",
  },
  {
    id: "e17",
    imageSrc: "/src/assets/Electronics/Tablet 10-inch.jpeg",
    title: "Tablet 10-inch",
    price: "Rs. 65,000",
    stars: 4,
    rates: 123,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "10-inch tablet perfect for entertainment, work, and creativity.",
  },
  {
    id: "e18",
    imageSrc: "/src/assets/Electronics/LED Monitor 24-inch.webp",
    title: "LED Monitor 24-inch",
    price: "Rs. 35,000",
    stars: 4,
    rates: 167,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "24-inch LED monitor with crisp display and wide viewing angles.",
  },
  {
    id: "e19",
    imageSrc: "/src/assets/Electronics/Graphics Card (GPU).jpeg",
    title: "Graphics Card (GPU)",
    price: "Rs. 150,000",
    stars: 5,
    rates: 34,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "High-performance graphics card for gaming and professional work.",
  },
  {
    id: "e20",
    imageSrc: "/src/assets/Electronics/Power Bank 20,000 mAh.jpeg",
    title: "Power Bank 20,000 mAh",
    price: "Rs. 8,000",
    stars: 4,
    rates: 289,
    discount: "",
    quantity: 0,
    type: "Electronics",
    details: "High-capacity power bank for extended device charging on the go.",
  },

  // Fashion Category (f1-f20)
  {
    id: "f1",
    imageSrc: "/src/assets/Fashion/MShirt.jpg",
    title: "Men's T-Shirt",
    price: "Rs. 2,500",
    stars: 4,
    rates: 312,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Comfortable and stylish men's t-shirt made from premium cotton.",
  },
  {
    id: "f2",
    imageSrc: "/src/assets/Fashion/WShirt.jpg",
    title: "Women's T-Shirt",
    price: "Rs. 2,800",
    stars: 4,
    rates: 298,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Elegant women's t-shirt with modern fit and soft fabric.",
  },
  {
    id: "f3",
    imageSrc: "/src/assets/Fashion/MJeans.jpg",
    title: "Men's Jeans",
    price: "Rs. 4,500",
    stars: 4,
    rates: 245,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Classic men's jeans with perfect fit and durable denim.",
  },
  {
    id: "f4",
    imageSrc: "/src/assets/Fashion/Wjeans.jpg",
    title: "Women's Jeans",
    price: "Rs. 5,000",
    stars: 4,
    rates: 267,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Stylish women's jeans with flattering cut and stretch comfort.",
  },
  {
    id: "f5",
    imageSrc: "/src/assets/Fashion/Hoodie.jpg",
    title: "Hoodie",
    price: "Rs. 4,000",
    stars: 4,
    rates: 189,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Warm and cozy hoodie perfect for casual wear and outdoor activities.",
  },
  {
    id: "f6",
    imageSrc: "/src/assets/Fashion/Dress.jpg",
    title: "Dress",
    price: "Rs. 6,500",
    stars: 5,
    rates: 156,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Elegant dress suitable for both casual and formal occasions.",
  },
  {
    id: "f7",
    imageSrc: "/src/assets/Fashion/Jacket.jpg",
    title: "Jacket",
    price: "Rs. 7,500",
    stars: 4,
    rates: 178,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Stylish jacket perfect for layering and cooler weather.",
  },
  {
    id: "f8",
    imageSrc: "/src/assets/Fashion/Sneakers.jpg",
    title: "Sneakers",
    price: "Rs. 6,000",
    stars: 4,
    rates: 234,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Comfortable sneakers with modern design and excellent support.",
  },
  {
    id: "f9",
    imageSrc: "/src/assets/Fashion/Sandals.jpg",
    title: "Sandals",
    price: "Rs. 3,000",
    stars: 4,
    rates: 198,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Lightweight sandals perfect for summer and casual wear.",
  },
  {
    id: "f10",
    imageSrc: "/src/assets/Fashion/Formal Shoes.jpg",
    title: "Formal Shoes",
    price: "Rs. 8,000",
    stars: 4,
    rates: 145,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Professional formal shoes for business and formal occasions.",
  },
  {
    id: "f11",
    imageSrc: "/src/assets/Fashion/Handbag.jpg",
    title: "Handbag",
    price: "Rs. 5,500",
    stars: 4,
    rates: 167,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Stylish handbag with multiple compartments and durable construction.",
  },
  {
    id: "f12",
    imageSrc: "/src/assets/Fashion/backpack.jpg",
    title: "Backpack",
    price: "Rs. 4,500",
    stars: 4,
    rates: 223,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Functional backpack perfect for daily use and travel.",
  },
  {
    id: "f13",
    imageSrc: "/src/assets/Fashion/Belt.jpg",
    title: "Belt",
    price: "Rs. 1,500",
    stars: 4,
    rates: 289,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Classic leather belt with durable buckle and adjustable fit.",
  },
  {
    id: "f14",
    imageSrc: "/src/assets/Fashion/Sunglasses.jpg",
    title: "Sunglasses",
    price: "Rs. 2,500",
    stars: 4,
    rates: 178,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Stylish sunglasses with UV protection and modern frame design.",
  },
  {
    id: "f15",
    imageSrc: "/src/assets/Fashion/Watch.jpg",
    title: "Watch",
    price: "Rs. 10,000",
    stars: 5,
    rates: 134,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Elegant watch with precise movement and sophisticated design.",
  },
  {
    id: "f16",
    imageSrc: "/src/assets/Fashion/Cap.jpg",
    title: "Cap",
    price: "Rs. 1,800",
    stars: 4,
    rates: 245,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Comfortable cap perfect for outdoor activities and casual wear.",
  },
  {
    id: "f17",
    imageSrc: "/src/assets/Fashion/Scarf.jpg",
    title: "Scarf",
    price: "Rs. 1,200",
    stars: 4,
    rates: 198,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Soft scarf made from premium materials for warmth and style.",
  },
  {
    id: "f18",
    imageSrc: "/src/assets/Fashion/Socks.jpg",
    title: "Socks",
    price: "Rs. 800",
    stars: 4,
    rates: 456,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Comfortable socks with cushioning and breathable fabric.",
  },
  {
    id: "f19",
    imageSrc: "/src/assets/Fashion/Leggings.jpg",
    title: "Leggings",
    price: "Rs. 2,000",
    stars: 4,
    rates: 234,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Comfortable leggings perfect for workouts and casual wear.",
  },
  {
    id: "f20",
    imageSrc: "/src/assets/Fashion/Skirt.jpg",
    title: "Skirt",
    price: "Rs. 3,500",
    stars: 4,
    rates: 189,
    discount: "",
    quantity: 0,
    type: "Fashion",
    details: "Elegant skirt with flattering fit and versatile styling options.",
  },

  // Kitchen & Dining Category (hk1-hk20)
  {
    id: "hk1",
    imageSrc: "/src/assets/KitchenAndDining/Blender.jpg",
    title: "Blender",
    price: "Rs. 15,000",
    stars: 4,
    rates: 167,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Powerful blender perfect for smoothies, soups, and food preparation.",
  },
  {
    id: "hk2",
    imageSrc: "/src/assets/KitchenAndDining/Air Fryer.jpeg",
    title: "Air Fryer",
    price: "Rs. 25,000",
    stars: 5,
    rates: 134,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Healthy cooking air fryer with digital controls and multiple cooking modes.",
  },
  {
    id: "hk3",
    imageSrc: "/src/assets/KitchenAndDining/Toaster.jpg",
    title: "Toaster",
    price: "Rs. 7,500",
    stars: 4,
    rates: 223,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "2-slice toaster with adjustable browning control and crumb tray.",
  },
  {
    id: "hk4",
    imageSrc: "/src/assets/KitchenAndDining/Microwave Oven.jpeg",
    title: "Microwave Oven",
    price: "Rs. 40,000",
    stars: 4,
    rates: 145,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Convection microwave oven with multiple cooking functions and preset programs.",
  },
  {
    id: "hk5",
    imageSrc: "/src/assets/KitchenAndDining/Electric Kettle.jpg",
    title: "Electric Kettle",
    price: "Rs. 5,500",
    stars: 4,
    rates: 289,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Fast-boiling electric kettle with auto-shutoff and water level indicator.",
  },
  {
    id: "hk6",
    imageSrc: "/src/assets/KitchenAndDining/Coffee Maker.jpeg",
    title: "Coffee Maker",
    price: "Rs. 12,000",
    stars: 4,
    rates: 178,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Programmable coffee maker with thermal carafe and multiple brew sizes.",
  },
  {
    id: "hk7",
    imageSrc: "/src/assets/KitchenAndDining/Juicer.webp",
    title: "Juicer",
    price: "Rs. 18,000",
    stars: 4,
    rates: 123,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Centrifugal juicer for fresh fruit and vegetable juices.",
  },
  {
    id: "hk8",
    imageSrc: "/src/assets/KitchenAndDining/Rice Cooker.jpeg",
    title: "Rice Cooker",
    price: "Rs. 10,000",
    stars: 4,
    rates: 234,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Automatic rice cooker with keep-warm function and multiple cooking modes.",
  },
  {
    id: "hk9",
    imageSrc: "/src/assets/KitchenAndDining/Gas Stove.jpeg",
    title: "Gas Stove",
    price: "Rs. 35,000",
    stars: 4,
    rates: 89,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "4-burner gas stove with electronic ignition and safety features.",
  },
  {
    id: "hk10",
    imageSrc: "/src/assets/KitchenAndDining/Non-stick Frying Pan.jpeg",
    title: "Non-stick Frying Pan",
    price: "Rs. 6,000",
    stars: 4,
    rates: 267,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Durable non-stick frying pan perfect for everyday cooking.",
  },
  {
    id: "hk11",
    imageSrc: "/src/assets/KitchenAndDining/Knife Set.jpg",
    title: "Knife Set",
    price: "Rs. 8,500",
    stars: 4,
    rates: 189,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Professional knife set with wooden block and sharpening steel.",
  },
  {
    id: "hk12",
    imageSrc: "/src/assets/KitchenAndDining/Cutting Board Set.jpg",
    title: "Cutting Board Set",
    price: "Rs. 3,500",
    stars: 4,
    rates: 312,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Set of cutting boards in different sizes for various food preparation needs.",
  },
  {
    id: "hk13",
    imageSrc: "/src/assets/KitchenAndDining/Pressure Cooker.jpeg",
    title: "Pressure Cooker",
    price: "Rs. 12,500",
    stars: 4,
    rates: 156,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Stainless steel pressure cooker for fast and healthy cooking.",
  },
  {
    id: "hk14",
    imageSrc: "/src/assets/KitchenAndDining/Blender Bottle.jpeg",
    title: "Blender Bottle",
    price: "Rs. 2,000",
    stars: 4,
    rates: 445,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Leak-proof blender bottle perfect for protein shakes and smoothies.",
  },
  {
    id: "hk15",
    imageSrc: "/src/assets/KitchenAndDining/Food Storage Containers.jpeg",
    title: "Food Storage Containers",
    price: "Rs. 3,000",
    stars: 4,
    rates: 298,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Set of airtight food storage containers for organized kitchen storage.",
  },
  {
    id: "hk16",
    imageSrc: "/src/assets/KitchenAndDining/Dish Rack.webp",
    title: "Dish Rack",
    price: "Rs. 2,500",
    stars: 4,
    rates: 234,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Sturdy dish rack for organized dish drying and storage.",
  },
  {
    id: "hk17",
    imageSrc: "/src/assets/KitchenAndDining/Electric Grill.jpg",
    title: "Electric Grill",
    price: "Rs. 14,000",
    stars: 4,
    rates: 167,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Indoor electric grill perfect for healthy grilling year-round.",
  },
  {
    id: "hk18",
    imageSrc: "/src/assets/KitchenAndDining/Oven Mitts.jpg",
    title: "Oven Mitts",
    price: "Rs. 1,200",
    stars: 4,
    rates: 378,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Heat-resistant oven mitts for safe handling of hot dishes.",
  },
  {
    id: "hk19",
    imageSrc: "/src/assets/KitchenAndDining/Tableware Set.jpg",
    title: "Tableware Set",
    price: "Rs. 5,500",
    stars: 4,
    rates: 198,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Complete tableware set for elegant dining experiences.",
  },
  {
    id: "hk20",
    imageSrc: "/src/assets/KitchenAndDining/Ceramic Cooking Pot.jpg",
    title: "Ceramic Cooking Pot",
    price: "Rs. 8,500",
    stars: 4,
    rates: 145,
    discount: "",
    quantity: 0,
    type: "Kitchen & Dining",
    details: "Non-stick ceramic cooking pot perfect for healthy cooking.",
  },

  // Beauty & Personal Care Category (bp1-bp20)
  {
    id: "bp1",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Facial Cleanser.png",
    title: "Facial Cleanser",
    price: "Rs. 1,200",
    stars: 4,
    rates: 456,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Gentle facial cleanser for all skin types with natural ingredients.",
  },
  {
    id: "bp2",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Moisturizer.jpg",
    title: "Moisturizer",
    price: "Rs. 1,500",
    stars: 4,
    rates: 398,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Hydrating moisturizer for soft and supple skin.",
  },
  {
    id: "bp3",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Sunscreen SPF 50.jpg",
    title: "Sunscreen SPF 50",
    price: "Rs. 1,800",
    stars: 4,
    rates: 345,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Broad-spectrum sunscreen with SPF 50 for complete sun protection.",
  },
  {
    id: "bp4",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Shampoo.jpg",
    title: "Shampoo",
    price: "Rs. 900",
    stars: 4,
    rates: 567,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Nourishing shampoo for healthy and shiny hair.",
  },
  {
    id: "bp5",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Conditioner.jpg",
    title: "Conditioner",
    price: "Rs. 900",
    stars: 4,
    rates: 523,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Smoothing conditioner for soft and manageable hair.",
  },
  {
    id: "bp6",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Body Lotion.jpg",
    title: "Body Lotion",
    price: "Rs. 1,200",
    stars: 4,
    rates: 412,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Hydrating body lotion for smooth and moisturized skin.",
  },
  {
    id: "bp7",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Lip Balm.jpg",
    title: "Lip Balm",
    price: "Rs. 500",
    stars: 4,
    rates: 678,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Moisturizing lip balm for soft and protected lips.",
  },
  {
    id: "bp8",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Hair Oil.jpg",
    title: "Hair Oil",
    price: "Rs. 700",
    stars: 4,
    rates: 445,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Nourishing hair oil for healthy and strong hair.",
  },
  {
    id: "bp9",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Perfume.jpg",
    title: "Perfume",
    price: "Rs. 2,500",
    stars: 5,
    rates: 234,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Elegant perfume with long-lasting fragrance.",
  },
  {
    id: "bp10",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Makeup Kit.jpg",
    title: "Makeup Kit",
    price: "Rs. 3,500",
    stars: 4,
    rates: 189,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Complete makeup kit with essential cosmetics and tools.",
  },
  {
    id: "bp11",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Foundation.jpg",
    title: "Foundation",
    price: "Rs. 1,500",
    stars: 4,
    rates: 298,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Long-lasting foundation for flawless complexion.",
  },
  {
    id: "bp12",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Lipstick.jpg",
    title: "Lipstick",
    price: "Rs. 800",
    stars: 4,
    rates: 345,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Vibrant lipstick with rich color and smooth application.",
  },
  {
    id: "bp13",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Eyeliner.jpg",
    title: "Eyeliner",
    price: "Rs. 600",
    stars: 4,
    rates: 412,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Precise eyeliner for defined and dramatic eyes.",
  },
  {
    id: "bp14",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Nail Polish.jpg",
    title: "Nail Polish",
    price: "Rs. 500",
    stars: 4,
    rates: 567,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Long-lasting nail polish in beautiful colors.",
  },
  {
    id: "bp15",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Hair Dryer.jpg",
    title: "Hair Dryer",
    price: "Rs. 4,500",
    stars: 4,
    rates: 234,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Professional hair dryer with multiple heat and speed settings.",
  },
  {
    id: "bp16",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Electric Hair Straightener.jpg",
    title: "Electric Hair Straightener",
    price: "Rs. 5,000",
    stars: 4,
    rates: 198,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Ceramic hair straightener for smooth and straight hair.",
  },
  {
    id: "bp17",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Razor.jpg",
    title: "Razor",
    price: "Rs. 3,000",
    stars: 4,
    rates: 289,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Multi-blade razor for smooth and comfortable shaving.",
  },
  {
    id: "bp18",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Toothpaste.jpg",
    title: "Toothpaste",
    price: "Rs. 400",
    stars: 4,
    rates: 789,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Fresh toothpaste for clean and healthy teeth.",
  },
  {
    id: "bp19",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Toothbrush.jpg",
    title: "Toothbrush",
    price: "Rs. 300",
    stars: 4,
    rates: 856,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Soft-bristled toothbrush for gentle and effective cleaning.",
  },
  {
    id: "bp20",
    imageSrc: "/src/assets/BeautyAndPersonalCare/Face Mask.jpg",
    title: "Face Mask",
    price: "Rs. 600",
    stars: 4,
    rates: 445,
    discount: "",
    quantity: 0,
    type: "Beauty & Personal Care",
    details: "Hydrating face mask for refreshed and glowing skin.",
  },

  // Home & Living Category (hl1-hl20)
  {
    id: "hl1",
    imageSrc: "/src/assets/HomeAndLiving/Sofa Set.webp",
    title: "Sofa Set",
    price: "Rs. 120,000",
    stars: 5,
    rates: 67,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Elegant 3-seater sofa set perfect for living room comfort.",
  },
  {
    id: "hl2",
    imageSrc: "/src/assets/HomeAndLiving/Wooden Dining Table.jpg",
    title: "Wooden Dining Table",
    price: "Rs. 85,000",
    stars: 4,
    rates: 89,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Solid wood dining table with seating for 6 people.",
  },
  {
    id: "hl3",
    imageSrc: "/src/assets/HomeAndLiving/Office Chair.webp",
    title: "Office Chair",
    price: "Rs. 35,000",
    stars: 4,
    rates: 156,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Ergonomic office chair with adjustable features and lumbar support.",
  },
  {
    id: "hl4",
    imageSrc: "/src/assets/HomeAndLiving/Bookshelf.jpeg",
    title: "Bookshelf",
    price: "Rs. 22,000",
    stars: 4,
    rates: 234,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Spacious bookshelf with multiple shelves for organized storage.",
  },
  {
    id: "hl5",
    imageSrc: "/src/assets/HomeAndLiving/Wardrobe Cabinet.jpg",
    title: "Wardrobe Cabinet",
    price: "Rs. 75,000",
    stars: 4,
    rates: 123,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Large wardrobe cabinet with hanging space and drawers.",
  },
  {
    id: "hl6",
    imageSrc: "/src/assets/HomeAndLiving/Shoe Rack.jpg",
    title: "Shoe Rack",
    price: "Rs. 12,500",
    stars: 4,
    rates: 298,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Organized shoe rack for neat and tidy entryway.",
  },
  {
    id: "hl7",
    imageSrc: "/src/assets/HomeAndLiving/Coffee Table.jpg",
    title: "Coffee Table",
    price: "Rs. 18,000",
    stars: 4,
    rates: 178,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Stylish coffee table perfect for living room centerpiece.",
  },
  {
    id: "hl8",
    imageSrc: "/src/assets/HomeAndLiving/Bedside Table.jpeg",
    title: "Bedside Table",
    price: "Rs. 14,000",
    stars: 4,
    rates: 245,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Functional bedside table with storage drawer.",
  },
  {
    id: "hl9",
    imageSrc: "/src/assets/HomeAndLiving/Floor Lamp.webp",
    title: "Floor Lamp",
    price: "Rs. 9,500",
    stars: 4,
    rates: 189,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Modern floor lamp with adjustable head and ambient lighting.",
  },
  {
    id: "hl10",
    imageSrc: "/src/assets/HomeAndLiving/Wall Clock.webp",
    title: "Wall Clock",
    price: "Rs. 6,000",
    stars: 4,
    rates: 312,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Elegant wall clock with silent movement and classic design.",
  },
  {
    id: "hl11",
    imageSrc: "/src/assets/HomeAndLiving/Curtains.jpeg",
    title: "Curtains",
    price: "Rs. 8,000",
    stars: 4,
    rates: 267,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Beautiful curtains for privacy and style enhancement.",
  },
  {
    id: "hl12",
    imageSrc: "/src/assets/HomeAndLiving/Rug.jpeg",
    title: "Rug",
    price: "Rs. 15,000",
    stars: 4,
    rates: 198,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Soft area rug to add warmth and comfort to any room.",
  },
  {
    id: "hl13",
    imageSrc: "/src/assets/HomeAndLiving/Laundry Basket.jpeg",
    title: "Laundry Basket",
    price: "Rs. 4,500",
    stars: 4,
    rates: 345,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Spacious laundry basket with handles for easy carrying.",
  },
  {
    id: "hl14",
    imageSrc: "/src/assets/HomeAndLiving/Cushion Set.jpeg",
    title: "Cushion Set",
    price: "Rs. 3,800",
    stars: 4,
    rates: 234,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Comfortable cushion set to enhance seating comfort.",
  },
  {
    id: "hl15",
    imageSrc: "/src/assets/HomeAndLiving/Wall Shelf.jpg",
    title: "Wall Shelf",
    price: "Rs. 5,500",
    stars: 4,
    rates: 189,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Versatile wall shelf for displaying decorative items.",
  },
  {
    id: "hl16",
    imageSrc: "/src/assets/HomeAndLiving/Mirror.jpg",
    title: "Mirror",
    price: "Rs. 12,000",
    stars: 4,
    rates: 178,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Full-length mirror with elegant frame design.",
  },
  {
    id: "hl17",
    imageSrc: "/src/assets/HomeAndLiving/Table Lamp.webp",
    title: "Table Lamp",
    price: "Rs. 7,000",
    stars: 4,
    rates: 245,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Stylish table lamp perfect for bedside or desk lighting.",
  },
  {
    id: "hl18",
    imageSrc: "/src/assets/HomeAndLiving/Blanket.jpg",
    title: "Blanket",
    price: "Rs. 10,000",
    stars: 4,
    rates: 198,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Soft and warm blanket for cozy comfort.",
  },
  {
    id: "hl19",
    imageSrc: "/src/assets/HomeAndLiving/Bean Bag Chair.webp",
    title: "Bean Bag Chair",
    price: "Rs. 16,000",
    stars: 4,
    rates: 167,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Comfortable bean bag chair for casual seating.",
  },
  {
    id: "hl20",
    imageSrc: "/src/assets/HomeAndLiving/Wall Art Painting.jpg",
    title: "Wall Art Painting",
    price: "Rs. 9,000",
    stars: 4,
    rates: 123,
    discount: "",
    quantity: 0,
    type: "Home & Living",
    details: "Beautiful wall art painting to enhance room aesthetics.",
  },
];
